version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: postgres:11.1
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=test
        - PG_USER=postgres
        - PG_NAME=test

    steps:
      - checkout

      - run:
          name: Start server
          command: |
            git clone --depth 1 https://github.com/kids-first/kf-api-dataservice.git
            cd kf-api-dataservice
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install -e .
            flask db upgrade
            flask db migrate
            flask run
          background: true
          environment:
            - FLASK_APP: "manage"
            - PG_USER: "postgres"
            - PG_NAME: "test"

      - run:
          name: Do Tests
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r dev-requirements.txt
            pytest tests
