version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
      - image: postgres:11.1
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=test
        - PG_USER=postgres
        - PG_NAME=test

    steps:
      - checkout

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

      - run:
          name: start local dataservice
          command: |
            git clone --depth 1 https://github.com/kids-first/kf-api-dataservice.git
            cd kf-api-dataservice
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install -e .
            flask db upgrade
            flask db migrate
            flask run
          background: true
          environment:
            - FLASK_APP: "manage"
            - PG_USER: "postgres"
            - PG_NAME: "test"

      - run:
          name: run tests
          command: |
            dockerize -wait http://localhost:5000 -timeout 5m
            python3 -m venv venv
            source venv/bin/activate
            pip install -r dev-requirements.txt
            pytest tests
